In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
datos = pd.read_csv('../input/argentina-provincial-data/argentina.csv')

In [ ]:
po= datos.sort_values(by='poverty')

In [10]:
po.head(5)

,province,gdp,illiteracy,poverty,deficient_infra,school_dropout,no_healthcare,birth_mortal,pop,movie_theatres_per_cap,doctors_per_cap
9,La Pampa,6.990262e+06,1.53930,3.398774,16.505714,0.204093,45.4764,7.2,318951,0.000019,0.005415
2,Córdoba,6.936374e+07,2.71414,5.382380,10.436086,1.035056,45.7640,4.8,3308876,0.000011,0.010175
11,Mendoza,3.343137e+07,2.20020,5.692798,3.839852,1.063718,50.5843,4.4,1738929,0.000008,0.005720
19,Santa Fe,8.158869e+07,1.97594,6.081012,11.869195,2.872181,41.9660,2.6,3194537,0.000007,0.006672
17,San Luis,1.178085e+07,3.43365,6.593771,9.679894,2.000172,51.6154,3.8,432310,0.000005,0.006102

In [11]:
po.tail(5)

,province,gdp,illiteracy,poverty,deficient_infra,school_dropout,no_healthcare,birth_mortal,pop,movie_theatres_per_cap,doctors_per_cap
8,Jujuy,6.484938e+06,2.15139,13.367965,12.483179,0.721295,54.1615,3.7,673307,0.000003,0.003958
12,Misiones,9.646826e+06,6.86395,13.529788,8.325740,3.129124,57.8339,8.1,1101593,0.000002,0.002880
4,Chaco,9.832643e+06,7.51758,15.862619,31.479527,2.577462,65.5104,7.5,1055259,0.000003,0.003605
15,Salta,1.343883e+07,3.34609,16.870500,14.182303,1.482030,60.4230,5.8,1214441,0.000004,0.003991
7,Formosa,3.807057e+06,4.61064,17.035583,28.004985,2.268974,65.8126,16.2,530162,0.000004,0.003440

In [5]:
do= datos.sort_values(by='doctors_per_cap')

In [13]:
do.tail(5)

,province,gdp,illiteracy,poverty,deficient_infra,school_dropout,no_healthcare,birth_mortal,pop,movie_theatres_per_cap,doctors_per_cap
21,Tucumán,1.385620e+07,3.77037,11.214239,6.466665,0.977285,48.2242,3.0,1448188,0.000005,0.005501
11,Mendoza,3.343137e+07,2.20020,5.692798,3.839852,1.063718,50.5843,4.4,1738929,0.000008,0.005720
17,San Luis,1.178085e+07,3.43365,6.593771,9.679894,2.000172,51.6154,3.8,432310,0.000005,0.006102
19,Santa Fe,8.158869e+07,1.97594,6.081012,11.869195,2.872181,41.9660,2.6,3194537,0.000007,0.006672
2,Córdoba,6.936374e+07,2.71414,5.382380,10.436086,1.035056,45.7640,4.8,3308876,0.000011,0.010175

In [14]:
do.head(5)

,province,gdp,illiteracy,poverty,deficient_infra,school_dropout,no_healthcare,birth_mortal,pop,movie_theatres_per_cap,doctors_per_cap
20,Santiago del Estero,8.387859e+06,6.27209,11.759000,20.491433,2.325598,63.6637,1.7,874006,0.000003,0.002821
12,Misiones,9.646826e+06,6.86395,13.529788,8.325740,3.129124,57.8339,8.1,1101593,0.000002,0.002880
7,Formosa,3.807057e+06,4.61064,17.035583,28.004985,2.268974,65.8126,16.2,530162,0.000004,0.003440
4,Chaco,9.832643e+06,7.51758,15.862619,31.479527,2.577462,65.5104,7.5,1055259,0.000003,0.003605
8,Jujuy,6.484938e+06,2.15139,13.367965,12.483179,0.721295,54.1615,3.7,673307,0.000003,0.003958

In [7]:
nuse=datos['province']

In [8]:
co=nuse.loc[2]
fo=nuse.loc[7]
sa=nuse.loc[15]
san=nuse.loc[17]
sal=nuse.loc[18]

In [11]:
provincias = co,fo,sa,san,sal
provincias

('Córdoba', 'Formosa', 'Salta', 'San Luis', 'Santa Cruz')